config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  resources :lists do
    member do
      get 'new_entry'
      post 'entries', to: 'lists#create_entry'
      get 'iframe'
    end
  end

  resources :my_lists do
    member do
      get 'export'
    end
  end

  root to: 'lists#index'

end

app/models/list.rb
class List
  include Mongoid::Document
  # include Mongoid::OptimisticLocking
  include Mongoid::Timestamps

  field :name, type: String
  field :max_entries, type: Integer
  field :max_entries_per_user, type: Integer, default: 1

  belongs_to :owner, class_name: 'User'
  field :owner_full_name, type: String, default: "" # cache

  has_many :users

  embeds_many :list_fields, class_name: 'Field::Base'
  embeds_many :entries

  accepts_nested_attributes_for :list_fields, :reject_if => :all_blank, :allow_destroy => true

  validates_associated :list_fields
  validates_associated :entries
  validates_presence_of :name, :list_fields
  validates_numericality_of :max_entries, only_integer: true, greater_than: 0, if: -> { max_entries.present? }
  validates_numericality_of :max_entries_per_user, only_integer: true, greater_than: 0, if: -> { max_entries_per_user.present? }

  before_save do
    self.owner_full_name = owner.full_name
  end

  def public_list_fields(type = nil)
    @fields = list_fields.select {|f| f.public}
    @fields.select! {|f| f.is_a?(type)} if type.present?
    @fields
  end

  def why_cannot_enroll(user, new_record = false)
    reasons = []
    reasons << "too many entries on the list" if (max_entries.present? &&
      entries.count + (new_record ? 0 : 1) > max_entries)
    reasons << "you made too many entries" if (max_entries_per_user.present? &&
      entries.select{|e| e.user_id == user.id}.count + (new_record ? 0 : 1) > max_entries_per_user)
    reasons
  end

  def can_enroll?(user)
    why_cannot_enroll(user).empty?
  end

  def instant_enroll?
    list_fields.select {|f| !f.is_a?(Field::User)}.empty?
  end

  def is_enroled?(user)
    entries.detect {|e| e.user == user }.present?
  end

  def fields_map
    @fields_map ||= Hash[list_fields.map {|f| [f.id, f]}]
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy, :new_entry, :create_entry, :iframe]
  before_action :check_user

  def new_entry
    @entry = @list.entries.new(entry_fields: @list.list_fields.map(&:build_entry_field))
  end

  def create_entry
    @entry = @list.entries.new(entry_params.merge(user: current_user))
    @entry.entry_fields << @list.list_fields.select {|a| a.is_a?(Field::User) }.map(&:build_entry_field)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @list, notice: "You've been enrolled successfully" }
        # format.json { render :show, status: :created, location: my_list_path(@list) }
      else
        format.html { render :new_entry }
        # format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def iframe
    render :iframe, layout: 'iframe'
  end

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      begin
        params.require(:entry).permit(entry_fields_attributes:
          [
            :_type,
            :field_id,
            :value,
            :option_id
          ]
        )
      rescue
        {}
      end
    end
end

app/helpers/lists_helper.rb
module ListsHelper
  def form_url
    action_name == 'edit' || action_name == 'update' ? my_list_path(@list) : my_lists_path
  end

  def user_public_fields_msg(list)
    fields = list.public_list_fields(Field::User)
    fields.count > 0 ? "You will publicly share your #{fields.map(&:name).join(', ')}" : nil
  end
end

app/views/lists/_enroll_button.html.haml
- if current_user
  - unless list.can_enroll? current_user
    %span.btn.btn-disabled.btn-primary.cannot_enroll{disabled: 'disabled', :"data-why-cannot-enroll" => list.why_cannot_enroll(current_user).join("<br/>")} 
      can't enroll
      = "(#{pluralize(list.entries.count,'entry')})"
  - else
    -if list.instant_enroll?
      = link_to "Enroll (#{pluralize(list.entries.count,'entry')} already)", entries_list_path(list), class: 'btn btn-primary instant-enroll', method: 'post', :"data-user-public-fields" => user_public_fields_msg(list)
    -else
      = link_to "Enroll (#{pluralize(list.entries.count,'entry')} already)", new_entry_list_path(list), class: 'btn btn-primary', target: '_blank'

app/views/lists/iframe.html.haml
%h3
  = @list.name
= render partial: 'enroll_button', locals: {list: @list}

app/views/lists/index.html.haml
%h1 Listing Lists
%table.table.table-striped.table-bordered
  %thead
    %tr
      %th Name
      %th Entries count
      %th Owner
      %th Actions
  %tbody
    - @lists.each do |list|
      %tr
        %td
          = list.name
        %td= list.entries.count
        %td
          = list.owner_full_name
        %td
          .btn-group
            = link_to 'Show', list, class: "btn btn-primary"
            = render partial: 'enroll_button', locals: {list: list}

app/views/lists/new_entry.html.haml
%h1
  = @list.name
  \:: new entry
= render 'entries/form'

app/views/lists/show.html.haml
%h1
  = @list.name
  %small
    by
    = @list.owner_full_name
  = render partial: 'enroll_button', locals: {list: @list}
%h3
  Enrolled count:
  = @list.entries.count

%h3 Fields
%ul
  - @list.list_fields.each do |f|
    %li
      = f.public ? "PUBLIC" : ""
      = f.model_name.human
      \::
      = f.name

%h4 Iframe embed code
%pre
  = "<iframe src=\"#{iframe_list_url(@list)}\" style=\"width:500px; height: 70px; border:none;\"></iframe>"
%h4 BBcode embed code
%pre
  = "[betterpoll=#{@list.id}][/betterpoll]"

/ .btn-group
/   = link_to 'Back', lists_path, class: "btn btn-default"

- if @list.public_list_fields.count > 0
  %h3 
    Entries
    %small displaying only public fields

  %table.table
    %thead
      %tr
        %th Created at
        - @list.public_list_fields.each do |f|
          %th= f.name.humanize
    %tbody
      
      - @list.entries.each do |e|
        %tr
          %td= e.created_at
          - @list.public_list_fields.each do |f|
            %td= e.entry_fields_map[f].value