config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  resources :lists do
    member do
      get 'new_entry'
      post 'entries', to: 'lists#create_entry'
      get 'iframe'
    end
  end

  resources :my_lists do
    member do
      get 'export'
    end
  end

  root to: 'lists#index'

end

app/controllers/my_lists_controller.rb
require 'csv'
class MyListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy, :export]
  before_action :check_user

  # GET /lists
  # GET /lists.json
  def index
    @lists = current_user.lists.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  def export
    csv = CSV.generate do |csv|
      csv << @list.list_fields.map {|f| f.name}
      @list.entries.each do |e|
        csv << @list.list_fields.map do |f|
          e.entry_fields_map[f].value
        end
      end
    end
    send_data csv, filename: "#{@list.name.parameterize}-#{Time.now.iso8601}.csv", type: 'text/csv'
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = current_user.lists.new(new_list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to my_list_path(@list), notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: my_list_path(@list) }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(existing_list_params)
        format.html { redirect_to my_list_path(@list), notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: my_list_path(@list) }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to my_lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def check_ownership
      raise NotAuthorized if @list.owner_id != current_user.id
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = current_user.lists.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def new_list_params
      params.require(:list).permit(:name, :max_entries, :max_entries_per_user,
      list_fields_attributes: 
        [
          :id,
          :_destroy,
          :_type,
          :name,
          :max_length,
          :required,
          :public,
          select_options_attributes:
            [
              :name,
              :id,
              :_destroy,
              :description,
              :max_entries
            ]
        ])
    end
    def existing_list_params
      params.require(:list).permit(:name, :max_entries, :max_entries_per_user)
    end
end

app/views/my_lists/_field_header.html.haml
%h4 
  = f.object.model_name.human
  = link_to_remove_association "remove field", f, class: "btn btn-sm btn-danger", style: "margin-bottom:15px"

app/views/my_lists/_form.html.haml
= simple_form_for(@list, url: form_url) do |f|
  = f.error_notification
  .form-inputs
    = f.input :name
    = f.input :max_entries
    = f.input :max_entries_per_user
    -if @list.new_record?
      %h3 Fields
      #list_fields
        = f.simple_fields_for :list_fields do |field|
          = render "entries/#{field.object.model_name.singular}", :f => field
        .links
          .btn-group
            = link_to_add_association 'Add user field', f, :list_fields, partial: 'entries/field_user', wrap_object: Proc.new {|o| Field::User.new(o.attributes) }, class: "btn btn-default"
            = link_to_add_association 'Add text field', f, :list_fields, partial: 'entries/field_text', wrap_object: Proc.new {|o| Field::Text.new(o.attributes) }, class: "btn btn-default"
            = link_to_add_association 'Add boolean field', f, :list_fields, partial: 'entries/field_boolean', wrap_object: Proc.new {|o| Field::Boolean.new(o.attributes) }, class: "btn btn-default"
            = link_to_add_association 'Add select field', f, :list_fields, partial: 'entries/field_select', wrap_object: Proc.new {|o| Field::Select.new(o.attributes) }, class: "btn btn-default"
  .form-actions
    .btn-group.pull-right
      = f.button :submit, class: "btn-success btn-lg"

app/views/my_lists/edit.html.haml
%h1 Editing List
= render 'form'

app/views/my_lists/index.html.haml
%h1 
  My lists
  = link_to 'New List', new_my_list_path, class: "btn btn-default btn-lg"
%table.table.table-striped.table-bordered
  %thead
    %tr
      %th Name
      %th Entries count
      %th Actions
  %tbody
    - @lists.each do |list|
      %tr
        %td
          = list.name
        %td
          = list.entries.count
        %td
          .btn-group
            = link_to 'Show', my_list_path(list), class: "btn btn-primary"
            = link_to 'Edit', edit_my_list_path(list), class: "btn btn-warning"
            / = link_to 'Destroy', my_list_path(list), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"

app/views/my_lists/new.html.haml
%h1 New List
= render 'form'

app/views/my_lists/show.html.haml
%h1
  = @list.name
  %small
    your list
  .btn-group.pull-right
    = link_to 'Edit', edit_my_list_path(@list), class: "btn btn-warning"
    = link_to 'Export to CSV', export_my_list_path(@list), class: "btn btn-default"
    = link_to 'Destroy', my_list_path(@list), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"

%h3
  Enrolled count:
  = @list.entries.count

%h3 Fields
%ul
  - @list.list_fields.each do |f|
    %li
      = f.public ? "PUBLIC" : ""
      = f.model_name.human
      \::
      = f.name

%h4 Iframe embed code
%pre
  = "<iframe src=\"#{iframe_list_url(@list)}\" style=\"width:500px; height: 70px; border:none;\"></iframe>"
%h4 BBcode embed code
%pre
  = "[betterpoll=#{@list.id}][/betterpoll]"

/ .btn-group
/   = link_to 'Back', lists_path, class: "btn btn-default"

- if @list.list_fields.count > 0
  %h3 
    Entries
    %small displaying all fields

  %table.table
    %thead
      %tr
        %th Created at
        - @list.list_fields.each do |f|
          %th= f.name.humanize
    %tbody
      
      - @list.entries.each do |e|
        %tr
          %td= e.created_at
          - @list.list_fields.each do |f|
            %td= e.entry_fields_map[f].value