config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  resources :lists do
    member do
      get 'new_entry'
      post 'entries', to: 'lists#create_entry'
      get 'iframe'
    end
  end

  resources :my_lists do
    member do
      get 'export'
    end
  end

  root to: 'lists#index'

end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", role: "alert"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %a.navbar-brand{href: root_path}
        %span{class: "glyphicon glyphicon-stats", 'aria-hidden' => "true"}
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Better pool'.upcase, root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to "Logout", destroy_user_session_path, method: :delete

app/views/layouts/_navigation_links.html.haml
%li{class: (controller_name == 'lists') ? 'active' : ''}= link_to 'Browse lists', lists_path
-p controller_name
%li{class: (controller_name == 'my_lists') ? 'active' : ''}= link_to 'My lists', my_lists_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Betterpoll
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/navigation'
    .container
      %main{:role => "main", style: 'padding-top: 10px'}
        = render 'layouts/messages'
        = yield

app/views/layouts/iframe.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title Betterpoll
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield